import {
  AUDIT_DEFAULTS,
  RENDER_DEFAULTS,
  SIMULATION_DEFAULTS,
} from "../defaults.js";

export const CONTROL_TARGET_TYPES = Object.freeze({
  uniform: "uniform",
  pipeline: "pipeline",
  object: "object",
  audit: "audit",
});

export const CONTROL_STATUSES = Object.freeze({
  live: "live",
  debugOnly: "debug-only",
});

export const CONTROL_HANDLERS = Object.freeze({
  simulation: "simulation",
  bloom: "bloom",
  scene: "scene",
  audit: "audit",
});

export const CONTROL_DEFINITIONS = Object.freeze([
  {
    key: "bloomEnabled",
    folder: "Bloom",
    label: "Enabled",
    defaultValue: true,
    targetType: CONTROL_TARGET_TYPES.pipeline,
    handler: CONTROL_HANDLERS.bloom,
    runtimePath: "pipeline.outputNode",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "bloomStrength",
    folder: "Bloom",
    label: "Strength",
    defaultValue: RENDER_DEFAULTS.bloomStrength,
    binding: { min: 0, max: 3, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.pipeline,
    handler: CONTROL_HANDLERS.bloom,
    runtimePath: "bloomPass.strength.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "bloomRadius",
    folder: "Bloom",
    label: "Radius",
    defaultValue: RENDER_DEFAULTS.bloomRadius,
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.pipeline,
    handler: CONTROL_HANDLERS.bloom,
    runtimePath: "bloomPass.radius.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "bloomThreshold",
    folder: "Bloom",
    label: "Extract Threshold",
    defaultValue: RENDER_DEFAULTS.bloomThreshold,
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.pipeline,
    handler: CONTROL_HANDLERS.bloom,
    runtimePath: "bloomPass.threshold.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "backgroundColor",
    folder: "Color",
    label: "Background",
    defaultValue: RENDER_DEFAULTS.backgroundColor,
    binding: { view: "color" },
    targetType: CONTROL_TARGET_TYPES.object,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "renderer.clearColor",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "volumeColor",
    folder: "Color",
    label: "Volume",
    defaultValue: RENDER_DEFAULTS.color,
    binding: { view: "color" },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uColor.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "surfaceColor",
    folder: "Color",
    label: "Surface",
    defaultValue: RENDER_DEFAULTS.surfaceColor,
    binding: { view: "color" },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uSurfaceColor.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "particleSpeed",
    folder: "Particles",
    label: "Speed",
    defaultValue: SIMULATION_DEFAULTS.particleSpeed,
    binding: { min: 1, max: 100, step: 1 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uParticleSpeed.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "particleSize",
    folder: "Particles",
    label: "Size",
    defaultValue: RENDER_DEFAULTS.particleSize,
    binding: { min: 0.001, max: 0.5, step: 0.001 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uParticleSize.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "rotationSpeed",
    folder: "Particles",
    label: "Rotation",
    defaultValue: RENDER_DEFAULTS.rotationSpeed,
    binding: { min: -12, max: 12, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.object,
    handler: CONTROL_HANDLERS.scene,
    runtimePath: "points.rotation.y",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "flowFieldStrength",
    folder: "Granular",
    label: "Strength",
    defaultValue: SIMULATION_DEFAULTS.flowFieldStrength,
    binding: { min: 0, max: 10, step: 0.1 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uFlowFieldStrength.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "flowFieldFrequency",
    folder: "Granular",
    label: "Frequency",
    defaultValue: SIMULATION_DEFAULTS.flowFieldFrequency,
    binding: { min: 0.01, max: 5, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uFlowFieldFrequency.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "flowFieldInfluence",
    folder: "Granular",
    label: "Influence",
    defaultValue: SIMULATION_DEFAULTS.flowFieldInfluence,
    binding: { min: 0, max: 2, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uFlowFieldInfluence.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "targetLerpThreshold",
    folder: "Granular",
    label: "Lerp Threshold",
    defaultValue: SIMULATION_DEFAULTS.distanceThreshold,
    binding: { min: 0, max: 5, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uDistanceThreshold.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "zeroPointPrecision",
    folder: "Granular",
    label: "Node Threshold",
    defaultValue: SIMULATION_DEFAULTS.threshold,
    binding: { min: 0.001, max: 0.1, step: 0.001 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uThreshold.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "surfaceParticles",
    folder: "Aesthetics",
    label: "Surface",
    defaultValue: true,
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uSurfaceControl.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "particleMovementType",
    folder: "Aesthetics",
    label: "Movement",
    defaultValue: "Smoothed",
    binding: {
      options: {
        Quickest: "Quickest",
        Smoothed: "Smoothed",
      },
    },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uParticleMovementType.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "idleLogoIntensity",
    folder: "Idle Logo",
    label: "Intensity",
    defaultValue: RENDER_DEFAULTS.idleLogoIntensity,
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uIdleLogoIntensity.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "idleLogoAlpha",
    folder: "Idle Logo",
    label: "Alpha",
    defaultValue: RENDER_DEFAULTS.idleLogoAlpha,
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uIdleLogoAlpha.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "idleLogoSize",
    folder: "Idle Logo",
    label: "Scale",
    defaultValue: RENDER_DEFAULTS.idleLogoSize,
    binding: { min: 0.1, max: 2, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.simulation,
    runtimePath: "tsl.uniforms.uIdleLogoSize.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "auditEnabled",
    folder: "Audit",
    label: "Enabled",
    defaultValue: AUDIT_DEFAULTS.auditEnabled,
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.enabled",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "freezeModeSlots",
    folder: "Audit",
    label: "Freeze Slots",
    defaultValue: AUDIT_DEFAULTS.freezeModeSlots,
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.freezeModeSlots",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "injectTestTone",
    folder: "Audit",
    label: "Inject Tone",
    defaultValue: AUDIT_DEFAULTS.injectTestTone,
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.injectTestTone",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "pitchSourceMode",
    folder: "Audit",
    label: "Pitch Source",
    defaultValue: AUDIT_DEFAULTS.pitchSourceMode,
    binding: {
      options: {
        Auto: "auto",
        Worker: "worker",
        Fallback: "fallback",
      },
    },
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.pitchSourceMode",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "testToneHz",
    folder: "Audit",
    label: "Tone Hz",
    defaultValue: AUDIT_DEFAULTS.testToneHz,
    binding: { min: 40, max: 2000, step: 1 },
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.testToneHz",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "testToneAmplitude",
    folder: "Audit",
    label: "Tone Amp",
    defaultValue: AUDIT_DEFAULTS.testToneAmplitude,
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.testToneAmplitude",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "logEveryFrames",
    folder: "Audit",
    label: "Log Frames",
    defaultValue: AUDIT_DEFAULTS.logEveryFrames,
    binding: { min: 1, max: 240, step: 1 },
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.logEveryFrames",
    status: CONTROL_STATUSES.debugOnly,
  },
]);

export function createControlState() {
  return CONTROL_DEFINITIONS.reduce((state, definition) => {
    state[definition.key] = definition.defaultValue;
    return state;
  }, {});
}

export function getControlFolders() {
  return [...new Set(CONTROL_DEFINITIONS.map((definition) => definition.folder))];
}

export function getControlsForFolder(folder) {
  return CONTROL_DEFINITIONS.filter((definition) => definition.folder === folder);
}
