import {
  AUDIT_DEFAULTS,
  RENDER_DEFAULTS,
  SIMULATION_DEFAULTS,
} from "../defaults.js";
import { VISUALIZATION_METHODS } from "../visualization/types.js";

export const CONTROL_TARGET_TYPES = Object.freeze({
  uniform: "uniform",
  pipeline: "pipeline",
  object: "object",
  audit: "audit",
});

export const CONTROL_STATUSES = Object.freeze({
  live: "live",
  debugOnly: "debug-only",
});

export const CONTROL_HANDLERS = Object.freeze({
  shared: "shared",
  particle: "particle",
  bloom: "bloom",
  scene: "scene",
  audit: "audit",
});

export const CONTROL_DEFINITIONS = Object.freeze([
  {
    key: "bloomEnabled",
    folder: "Bloom",
    label: "Enabled",
    defaultValue: true,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    targetType: CONTROL_TARGET_TYPES.pipeline,
    handler: CONTROL_HANDLERS.bloom,
    runtimePath: "pipeline.outputNode",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "bloomStrength",
    folder: "Bloom",
    label: "Strength",
    defaultValue: RENDER_DEFAULTS.bloomStrength,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    binding: { min: 0, max: 3, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.pipeline,
    handler: CONTROL_HANDLERS.bloom,
    runtimePath: "bloomPass.strength.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "bloomRadius",
    folder: "Bloom",
    label: "Radius",
    defaultValue: RENDER_DEFAULTS.bloomRadius,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.pipeline,
    handler: CONTROL_HANDLERS.bloom,
    runtimePath: "bloomPass.radius.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "bloomThreshold",
    folder: "Bloom",
    label: "Extract Threshold",
    defaultValue: RENDER_DEFAULTS.bloomThreshold,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.pipeline,
    handler: CONTROL_HANDLERS.bloom,
    runtimePath: "bloomPass.threshold.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "backgroundColor",
    folder: "Color",
    label: "Background",
    defaultValue: RENDER_DEFAULTS.backgroundColor,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    binding: { view: "color" },
    targetType: CONTROL_TARGET_TYPES.object,
    handler: CONTROL_HANDLERS.shared,
    runtimePath: "renderer.clearColor",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "volumeColor",
    folder: "Color",
    label: "Volume",
    defaultValue: RENDER_DEFAULTS.color,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { view: "color" },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uColor.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "surfaceColor",
    folder: "Color",
    label: "Surface",
    defaultValue: RENDER_DEFAULTS.surfaceColor,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { view: "color" },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uSurfaceColor.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "particleSpeed",
    folder: "Particles",
    label: "Speed",
    defaultValue: SIMULATION_DEFAULTS.particleSpeed,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 1, max: 100, step: 1 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uParticleSpeed.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "particleSize",
    folder: "Particles",
    label: "Size",
    defaultValue: RENDER_DEFAULTS.particleSize,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0.001, max: 0.5, step: 0.001 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uParticleSize.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "rotationSpeed",
    folder: "Particles",
    label: "Rotation",
    defaultValue: RENDER_DEFAULTS.rotationSpeed,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: -12, max: 12, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.object,
    handler: CONTROL_HANDLERS.scene,
    runtimePath: "points.rotation.y",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "flowFieldStrength",
    folder: "Granular",
    label: "Strength",
    defaultValue: SIMULATION_DEFAULTS.flowFieldStrength,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 10, step: 0.1 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uFlowFieldStrength.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "flowFieldFrequency",
    folder: "Granular",
    label: "Frequency",
    defaultValue: SIMULATION_DEFAULTS.flowFieldFrequency,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0.01, max: 5, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uFlowFieldFrequency.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "zeroPointPrecision",
    folder: "Granular",
    label: "Node Threshold",
    defaultValue: SIMULATION_DEFAULTS.threshold,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0.001, max: 0.1, step: 0.001 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uThreshold.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "flowMix",
    folder: "Granular",
    label: "Flow Mix",
    defaultValue: SIMULATION_DEFAULTS.flowMix,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uFlowMix.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "attractionStrength",
    folder: "Granular",
    label: "Attraction",
    defaultValue: SIMULATION_DEFAULTS.attractionStrength,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 30, step: 0.1 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uAttractionStrength.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "velocityDamping",
    folder: "Granular",
    label: "Damping",
    defaultValue: SIMULATION_DEFAULTS.velocityDamping,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uVelocityDamping.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "centerSuppressionInner",
    folder: "Granular",
    label: "Center Inner",
    defaultValue: SIMULATION_DEFAULTS.centerSuppressionInner,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uCenterSuppressionInner.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "centerSuppressionOuter",
    folder: "Granular",
    label: "Center Outer",
    defaultValue: SIMULATION_DEFAULTS.centerSuppressionOuter,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uCenterSuppressionOuter.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "structureMin",
    folder: "Granular",
    label: "Structure Min",
    defaultValue: SIMULATION_DEFAULTS.structureMin,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uStructureMin.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "structureMax",
    folder: "Granular",
    label: "Structure Max",
    defaultValue: SIMULATION_DEFAULTS.structureMax,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uStructureMax.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "surfaceParticles",
    folder: "Aesthetics",
    label: "Surface",
    defaultValue: true,
    methods: [VISUALIZATION_METHODS.particle],
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uSurfaceControl.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "idleLogoIntensity",
    folder: "Idle Logo",
    label: "Intensity",
    defaultValue: RENDER_DEFAULTS.idleLogoIntensity,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uIdleLogoIntensity.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "idleLogoAlpha",
    folder: "Idle Logo",
    label: "Alpha",
    defaultValue: RENDER_DEFAULTS.idleLogoAlpha,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uIdleLogoAlpha.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "idleLogoSize",
    folder: "Idle Logo",
    label: "Scale",
    defaultValue: RENDER_DEFAULTS.idleLogoSize,
    methods: [VISUALIZATION_METHODS.particle],
    binding: { min: 0.1, max: 2, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.uniform,
    handler: CONTROL_HANDLERS.particle,
    runtimePath: "tsl.uniforms.uIdleLogoSize.value",
    status: CONTROL_STATUSES.live,
  },
  {
    key: "auditEnabled",
    folder: "Audit",
    label: "Enabled",
    defaultValue: AUDIT_DEFAULTS.auditEnabled,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.enabled",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "freezeModeSlots",
    folder: "Audit",
    label: "Freeze Slots",
    defaultValue: AUDIT_DEFAULTS.freezeModeSlots,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.freezeModeSlots",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "injectTestTone",
    folder: "Audit",
    label: "Inject Tone",
    defaultValue: AUDIT_DEFAULTS.injectTestTone,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.injectTestTone",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "pitchSourceMode",
    folder: "Audit",
    label: "Pitch Source",
    defaultValue: AUDIT_DEFAULTS.pitchSourceMode,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    binding: {
      options: {
        Auto: "auto",
        Worker: "worker",
        Fallback: "fallback",
      },
    },
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.pitchSourceMode",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "testToneHz",
    folder: "Audit",
    label: "Tone Hz",
    defaultValue: AUDIT_DEFAULTS.testToneHz,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    binding: { min: 40, max: 2000, step: 1 },
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.testToneHz",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "testToneAmplitude",
    folder: "Audit",
    label: "Tone Amp",
    defaultValue: AUDIT_DEFAULTS.testToneAmplitude,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    binding: { min: 0, max: 1, step: 0.01 },
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.testToneAmplitude",
    status: CONTROL_STATUSES.debugOnly,
  },
  {
    key: "logEveryFrames",
    folder: "Audit",
    label: "Log Frames",
    defaultValue: AUDIT_DEFAULTS.logEveryFrames,
    methods: [VISUALIZATION_METHODS.particle, VISUALIZATION_METHODS.raymarch],
    binding: { min: 1, max: 240, step: 1 },
    targetType: CONTROL_TARGET_TYPES.audit,
    handler: CONTROL_HANDLERS.audit,
    runtimePath: "featureState.audit.settings.logEveryFrames",
    status: CONTROL_STATUSES.debugOnly,
  },
]);

export function createControlState() {
  return CONTROL_DEFINITIONS.reduce((state, definition) => {
    state[definition.key] = definition.defaultValue;
    return state;
  }, {});
}

export function getControlsForMethod(method = VISUALIZATION_METHODS.particle) {
  return CONTROL_DEFINITIONS.filter((definition) => definition.methods.includes(method));
}

export function getControlFolders(method = VISUALIZATION_METHODS.particle) {
  return [...new Set(getControlsForMethod(method).map((definition) => definition.folder))];
}

export function getControlsForFolder(
  folder,
  method = VISUALIZATION_METHODS.particle
) {
  return getControlsForMethod(method).filter(
    (definition) => definition.folder === folder
  );
}
