const CALIBRATED_CLARITY_VISUAL_PRESET = Object.freeze({
  name: "Calibrated Clarity",
  builtIn: true,
  controls: Object.freeze({
    raymarchSteps: 88,
    zeroPointPrecision: 0.018,
    structureMin: 0.36,
    structureMax: 0.48,
    densityGain: 2.85,
    absorption: 3.05,
    opacityGain: 2.05,
    contourSharpness: 8,
    rimBloomBias: 0.2,
    rimCompression: 1.08,
    holographicIntensity: 0.36,
    holographicShift: 0.35,
    holographicFresnelPower: 5.1,
    bloomEnabled: true,
    bloomStrength: 0.94,
    bloomRadius: 0,
    bloomThreshold: 0.2,
    bloomResponseBias: 0.86,
    colorMode: "spectral",
    spectralMix: 1,
  }),
});

const STAGE_CONTAINMENT_VISUAL_PRESET = Object.freeze({
  name: "Stage Containment",
  builtIn: true,
  controls: Object.freeze({
    raymarchSteps: 88,
    zeroPointPrecision: 0.02,
    structureMin: 0.36,
    structureMax: 0.42,
    densityGain: 2.85,
    absorption: 3.75,
    opacityGain: 2.85,
    contourSharpness: 8,
    rimBloomBias: 0.22,
    rimCompression: 0.9,
    holographicIntensity: 0.46,
    holographicShift: 0.35,
    holographicFresnelPower: 4.2,
    bloomEnabled: true,
    bloomStrength: 0.82,
    bloomRadius: 0,
    bloomThreshold: 0.42,
    bloomResponseBias: 0.72,
    colorMode: "spectral",
    spectralMix: 0.95,
  }),
});

const BARYON_4_VISUAL_PRESET = Object.freeze({
  name: "baryon-4",
  builtIn: true,
  controls: Object.freeze({
    raymarchSteps: 104,
    zeroPointPrecision: 0.018,
    structureMin: 0.38,
    structureMax: 0.46,
    densityGain: 3.08,
    absorption: 3.62,
    opacityGain: 2.7,
    contourSharpness: 8,
    rimBloomBias: 0.26,
    rimCompression: 1.02,
    holographicIntensity: 0.52,
    holographicShift: 0.42,
    holographicFresnelPower: 4.8,
    bloomEnabled: true,
    bloomStrength: 0.76,
    bloomRadius: 0,
    bloomThreshold: 0.46,
    bloomResponseBias: 0.82,
    colorMode: "spectral",
    spectralMix: 0.92,
  }),
});

const BARYON_7_VISUAL_PRESET = Object.freeze({
  name: "baryon-7",
  builtIn: true,
  controls: Object.freeze({
    raymarchSteps: 80,
    zeroPointPrecision: 0.064,
    structureMin: 0.59,
    structureMax: 0.83,
    densityGain: 2.5,
    absorption: 1.45,
    opacityGain: 2.3,
    contourSharpness: 8,
    rimBloomBias: 0.39,
    rimCompression: 1.2,
    holographicIntensity: 0.52,
    holographicShift: 0.42,
    holographicFresnelPower: 4.8,
    rotationMode: "off",
    bloomEnabled: true,
    bloomStrength: 0.8,
    bloomRadius: 0,
    bloomThreshold: 0.24,
    bloomResponseBias: 1,
    colorMode: "spectral",
    spectralMix: 0.96,
    renderQualityPreset: "max-quality",
  }),
});

export const BUILT_IN_VISUAL_PRESETS = Object.freeze([
  CALIBRATED_CLARITY_VISUAL_PRESET,
  STAGE_CONTAINMENT_VISUAL_PRESET,
  BARYON_4_VISUAL_PRESET,
  BARYON_7_VISUAL_PRESET,
]);
