packages:
  - "apps/*"
  - "packages/*"

nodeLinker: hoisted

minimumReleaseAgeExclude:
  - "astro@7.0.0-beta.3"
  - "electron@42.3.3"

blockExoticSubdeps: false

allowBuilds:
  "@ast-grep/cli": true
  electron: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  sharp: true
