// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4dvBXLce6aZWcodsHuZ7oL
// Component: GPPFyGZ_p6O7
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import Button2 from "../../Button2"; // plasmic-import: EPGJPtXx-yjL/component
import { useScreenVariants as useScreenVariantspcuqpuXkf7V2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PcuqpuXKF7v2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4dvBXLce6aZWcodsHuZ7oL/projectcss
import sty from "./PlasmicNavBar.module.css"; // plasmic-import: GPPFyGZ_p6O7/css
import HamburgerMenuSvgrepoComSvgIcon from "./icons/PlasmicIcon__HamburgerMenuSvgrepoComSvg"; // plasmic-import: yQSNegzl0PI8/icon
import ClosebuttonSvgIcon from "./icons/PlasmicIcon__ClosebuttonSvg"; // plasmic-import: LiXFu_pZNIFT/icon

createPlasmicElementProxy;

export const PlasmicNavBar__VariantProps = new Array();

export const PlasmicNavBar__ArgProps = new Array();

const $$ = {};

function PlasmicNavBar__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspcuqpuXkf7V2()
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <NavigationBar
        data-plasmic-name={"navigationBar"}
        data-plasmic-override={overrides.navigationBar}
        brand={
          <Stack__
            as={"div"}
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <Stack__
              as={PlasmicLink__}
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              hasGap={true}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              href={`/`}
              platform={"react"}
            >
              <PlasmicImg__
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"25px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMzkxIDIwNDgiPgogIDxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNMjM5MC4yMSAxMi4zODVjLTQ4OS43OCA3Ni42MTMtODY0LjQ4IDUwMC4zNzItODY0LjQ4IDEwMTEuNjQ1IDAgNTExLjIxIDM3NC42IDkzNC45MiA4NjQuMjcgMTAxMS42Mi01MS45OCA4LjEzLTEwNS4yNiAxMi4zNS0xNTkuNTIgMTIuMzUtNTY1LjU0IDAtMTAyNC00NTguNDYtMTAyNC0xMDI0UzE2NjQuOTQgMCAyMjMwLjQ4IDBjNTQuMzMgMCAxMDcuNjggNC4yMzIgMTU5LjczIDEyLjM4NXpNMCAxMi4zODVDNDg5Ljc3NCA4OC45OTggODY0LjQ3NiA1MTIuNzU3IDg2NC40NzYgMTAyNC4wM2MwIDUxMS4yMS0zNzQuNTk2IDkzNC45Mi04NjQuMjY4IDEwMTEuNjIgNTEuOTgyIDguMTMgMTA1LjI2IDEyLjM1IDE1OS41MjQgMTIuMzUgNTY1LjU0IDAgMTAyMy45OTgtNDU4LjQ2IDEwMjMuOTk4LTEwMjRTNzI1LjI3MiAwIDE1OS43MzIgMEMxMDUuMzk2IDAgNTIuMDQ4IDQuMjMyIDAgMTIuMzg1eiIgZmlsbD0iI2ZmZiIvPgo8L3N2Zz4K",
                  fullWidth: 2391,
                  fullHeight: 2048,
                  aspectRatio: 1.16748
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__z5Ww8
                )}
              >
                {"Baryon"}
              </div>
            </Stack__>
          </Stack__>
        }
        className={classNames("__wab_instance", sty.navigationBar)}
        closeButton={
          <ClosebuttonSvgIcon
            className={classNames(projectcss.all, sty.svg__i0YA)}
            role={"img"}
          />
        }
        itemsGap={8}
        menuItems={
          <React.Fragment>
            <Button2
              className={classNames("__wab_instance", sty.button2__gew12)}
              color2={"clear"}
              onClick={async event => {
                const $steps = {};
                $steps["goToHomepage"] = true
                  ? (() => {
                      const actionArgs = { destination: `/` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          location.assign(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToHomepage"] != null &&
                  typeof $steps["goToHomepage"] === "object" &&
                  typeof $steps["goToHomepage"].then === "function"
                ) {
                  $steps["goToHomepage"] = await $steps["goToHomepage"];
                }
              }}
              shape={"rounded"}
              size={"compact"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__y4KtW
                )}
              >
                {"Visualizer"}
              </div>
            </Button2>
            <Button2
              className={classNames("__wab_instance", sty.button2__jUlJw)}
              color2={"clear"}
              onClick={async event => {
                const $steps = {};
                $steps["goToPlugin"] = true
                  ? (() => {
                      const actionArgs = { destination: `/plugin` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          location.assign(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToPlugin"] != null &&
                  typeof $steps["goToPlugin"] === "object" &&
                  typeof $steps["goToPlugin"].then === "function"
                ) {
                  $steps["goToPlugin"] = await $steps["goToPlugin"];
                }
              }}
              shape={"rounded"}
              size={"compact"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3XqGq
                )}
              >
                {"Plugin"}
              </div>
            </Button2>
            <Button2
              className={classNames("__wab_instance", sty.button2__wVlx)}
              color2={"clear"}
              onClick={async event => {
                const $steps = {};
                $steps["goToStory"] = true
                  ? (() => {
                      const actionArgs = { destination: `/story` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          location.assign(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToStory"] != null &&
                  typeof $steps["goToStory"] === "object" &&
                  typeof $steps["goToStory"].then === "function"
                ) {
                  $steps["goToStory"] = await $steps["goToStory"];
                }
              }}
              shape={"rounded"}
              size={"compact"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hSciT
                )}
              >
                {"Story"}
              </div>
            </Button2>
            <Button2
              className={classNames("__wab_instance", sty.button2__nrRh)}
              color2={"clear"}
              link={"https://foundation.app/@Baryon"}
              shape={"rounded"}
              size={"compact"}
              target={true}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___19AkY
                )}
              >
                {"Art"}
              </div>
            </Button2>
          </React.Fragment>
        }
        openButton={
          <HamburgerMenuSvgrepoComSvgIcon
            className={classNames(projectcss.all, sty.svg__nzB6)}
            role={"img"}
          />
        }
        responsiveBreakpoint={768}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "navigationBar", "freeBox", "link", "img"],
  navigationBar: ["navigationBar", "freeBox", "link", "img"],
  freeBox: ["freeBox", "link", "img"],
  link: ["link", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavBar__ArgProps,
          internalVariantPropNames: PlasmicNavBar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavBar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavBar";
  } else {
    func.displayName = `PlasmicNavBar.${nodeName}`;
  }
  return func;
}

export const PlasmicNavBar = Object.assign(
  // Top-level PlasmicNavBar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    freeBox: makeNodeComponent("freeBox"),
    link: makeNodeComponent("link"),
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicNavBar
    internalVariantProps: PlasmicNavBar__VariantProps,
    internalArgProps: PlasmicNavBar__ArgProps
  }
);

export default PlasmicNavBar;
/* prettier-ignore-end */
