// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4dvBXLce6aZWcodsHuZ7oL
// Component: FXocl_OYx5HY
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import NavBar from "../../NavBar"; // plasmic-import: GPPFyGZ_p6O7/component
import Button2 from "../../Button2"; // plasmic-import: EPGJPtXx-yjL/component
import BaryonFooter from "../../BaryonFooter"; // plasmic-import: FKV3u0E4hZrB/component
import { useScreenVariants as useScreenVariantspcuqpuXkf7V2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PcuqpuXKF7v2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4dvBXLce6aZWcodsHuZ7oL/projectcss
import sty from "./PlasmicPlugin.module.css"; // plasmic-import: FXocl_OYx5HY/css
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: nK6pvnnbOK1R/icon
import TouchDesignerBlack01SvgIcon from "./icons/PlasmicIcon__TouchDesignerBlack01Svg"; // plasmic-import: 8C7P_NC_xAYn/icon
import ResolumelogoSvgIcon from "./icons/PlasmicIcon__ResolumelogoSvg"; // plasmic-import: AvlJVplI2x17/icon
import UeLogotype2023SplashScreenVerticalBlackSvg2Icon from "./icons/PlasmicIcon__UeLogotype2023SplashScreenVerticalBlackSvg2"; // plasmic-import: GGjxGWSc9SjB/icon
import AbletonLogoWineSvgIcon from "./icons/PlasmicIcon__AbletonLogoWineSvg"; // plasmic-import: NQIxgI55S_TJ/icon
import OpenBroadcasterSoftwareLogoWineSvgIcon from "./icons/PlasmicIcon__OpenBroadcasterSoftwareLogoWineSvg"; // plasmic-import: buvdmCRySlxv/icon
import Icon15Icon from "./icons/PlasmicIcon__Icon15"; // plasmic-import: rIruQm-TzSjY/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: F3iOqCFKuA-k/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: IYnmkRggg6dZ/icon

createPlasmicElementProxy;

export const PlasmicPlugin__VariantProps = new Array();

export const PlasmicPlugin__ArgProps = new Array("signUpForm");

const $$ = {};

function PlasmicPlugin__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspcuqpuXkf7V2()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"plugin"}
          data-plasmic-override={overrides.plugin}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.plugin
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___4WeKa)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___0VtLd)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"foreground"}
                data-plasmic-override={overrides.foreground}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iergP)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__yZ7Yx)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nyFx3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__moqxw
                        )}
                      >
                        {"SOUND YOU CAN SEE"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___356Z3
                      )}
                    >
                      {"Cymatic Music Visualizer "}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cX7Ce
                      )}
                    >
                      {"Transform sound into stunning visuals with our plugin."}
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__apHNd)}
                >
                  {renderPlasmicSlot({
                    defaultContents: null,
                    value: args.signUpForm
                  })}
                </Stack__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"section"}
              data-plasmic-name={"pluginDetails"}
              data-plasmic-override={overrides.pluginDetails}
              hasGap={true}
              className={classNames(projectcss.all, sty.pluginDetails)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"columns"}
                  data-plasmic-override={overrides.columns}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__xn5LY)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__dLydY)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a2G4F
                        )}
                      >
                        {"THE PLUGIN"}
                      </div>
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2
                        )}
                      >
                        {"Make your music & sound visible."}
                      </h2>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4KU5O
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>
                            {
                              "Plug Baryon into your software tools & experience cymatics in 3D. We use physics to reveal the true form of sound. \n\nWe created this plugin for: \n"
                            }
                          </React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"DJs"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {", "}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"VJs"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {", "}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"Producers"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {", "}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"Artists"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {", "}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"Game Developers"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {", "}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"Content"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {" "}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"Creators"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {" & others. "}
                          </span>
                          <React.Fragment>{"\n\n"}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"Live events"}
                          </span>
                          <React.Fragment>
                            {
                              " can use Baryon to add the sense of sight to music.\n\nCultivate your imagination."
                            }
                          </React.Fragment>
                        </React.Fragment>
                      </div>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__zvb4M)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rohVc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__aF7M1
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uG5Bw
                          )}
                        >
                          {"Feature set"}
                        </div>
                      </div>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__n4Bl
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bKpVi
                          )}
                        >
                          {"Media server & visual software tool compatibility"}
                        </div>
                        <Icon14Icon
                          className={classNames(projectcss.all, sty.svg__a3Fbf)}
                          role={"img"}
                        />
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bY73O
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zU9
                          )}
                        >
                          {"Instrument line-in & MIDI\nconnectivity"}
                        </div>
                        <Icon14Icon
                          className={classNames(projectcss.all, sty.svg__iy4MI)}
                          role={"img"}
                        />
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__x41Q1
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8WdPg
                          )}
                        >
                          {"Latest software updates"}
                        </div>
                        <Icon14Icon
                          className={classNames(projectcss.all, sty.svg__cMJlW)}
                          role={"img"}
                        />
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__hMFvo
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dJcwn
                          )}
                        >
                          {"More customization"}
                        </div>
                        <Icon14Icon
                          className={classNames(projectcss.all, sty.svg__hAmcQ)}
                          role={"img"}
                        />
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yhHwN
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jdBtf
                          )}
                        >
                          {"Surprises"}
                        </div>
                        <Icon14Icon
                          className={classNames(projectcss.all, sty.svg__oOxl9)}
                          role={"img"}
                        />
                      </Stack__>
                    </div>
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"compatibility"}
              data-plasmic-override={overrides.compatibility}
              hasGap={true}
              className={classNames(projectcss.all, sty.compatibility)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vZuV
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      data-plasmic-name={"h3"}
                      data-plasmic-override={overrides.h3}
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3
                      )}
                    >
                      {"Compatibility via NDI"}
                    </h3>
                  }

                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__a5S0A)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__txnHv)}>
                  <TouchDesignerBlack01SvgIcon
                    data-plasmic-name={"touchDesignerLogo"}
                    data-plasmic-override={overrides.touchDesignerLogo}
                    className={classNames(
                      projectcss.all,
                      sty.touchDesignerLogo
                    )}
                    role={"img"}
                  />
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__lLyhx)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__wTfh)}>
                  <ResolumelogoSvgIcon
                    data-plasmic-name={"resolumeLogo"}
                    data-plasmic-override={overrides.resolumeLogo}
                    className={classNames(projectcss.all, sty.resolumeLogo)}
                    role={"img"}
                  />
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__gv6F)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__kinlF)}>
                  <UeLogotype2023SplashScreenVerticalBlackSvg2Icon
                    data-plasmic-name={"unrealEngineLogo"}
                    data-plasmic-override={overrides.unrealEngineLogo}
                    className={classNames(projectcss.all, sty.unrealEngineLogo)}
                    role={"img"}
                  />
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uDksf)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__oNns)}>
                  <AbletonLogoWineSvgIcon
                    data-plasmic-name={"abletonLogo"}
                    data-plasmic-override={overrides.abletonLogo}
                    className={classNames(projectcss.all, sty.abletonLogo)}
                    role={"img"}
                  />
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__pMyv8)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__qLay5)}>
                  <OpenBroadcasterSoftwareLogoWineSvgIcon
                    data-plasmic-name={"obsLogo"}
                    data-plasmic-override={overrides.obsLogo}
                    className={classNames(projectcss.all, sty.obsLogo)}
                    role={"img"}
                  />
                </div>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pexYm
                )}
              >
                {"& More"}
              </div>
            </Stack__>
            <div
              data-plasmic-name={"pricing"}
              data-plasmic-override={overrides.pricing}
              className={classNames(projectcss.all, sty.pricing)}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox___65UUt)}
              />

              <Stack__
                as={"div"}
                data-plasmic-name={"foreground3"}
                data-plasmic-override={overrides.foreground3}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground3)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__yyjb6)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pZwbQ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e5Y8G
                      )}
                    >
                      {"Pricing Plan"}
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ns9TL
                    )}
                  >
                    {"Unlock the synergy of sound and sight"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__x8Wa2)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___3BDfX)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__zbWyZ)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__s5Jbc
                        )}
                      >
                        {"Pro LICENSE"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pWpNh
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {"Pay What You Think Is Fair, Starting at"}
                          </span>
                        </React.Fragment>
                      </div>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__unBA
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cHLlk
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nKxvW
                            )}
                          >
                            {"$"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pYqfS
                            )}
                          >
                            {"50"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qShHx
                          )}
                        >
                          {"/year"}
                        </div>
                      </Stack__>
                    </Stack__>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nxR3D)}
                    />

                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__wxDo)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mtVf8
                        )}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__yfo46
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__nKhG6
                            )}
                          >
                            <Icon15Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__lMKgz
                              )}
                              role={"img"}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ls25Z
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ht4Kz
                              )}
                            >
                              {
                                "Access the full suite of audio visualization tools"
                              }
                            </div>
                          </Stack__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jwd98
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__bxJmp
                            )}
                          >
                            <Icon15Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__hnMpb
                              )}
                              role={"img"}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__dggS6
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__phyfe
                              )}
                            >
                              {
                                "Seamlessly integrate into your existing creative software"
                              }
                            </div>
                          </Stack__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___3Goa1
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__gpKqG
                            )}
                          >
                            <Icon15Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__pD60C
                              )}
                              role={"img"}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___0DcKs
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jOsTu
                              )}
                            >
                              {"Priority updates and new feature releases"}
                            </div>
                          </Stack__>
                        </Stack__>
                      </Stack__>
                      <Button2
                        data-plasmic-name={"button2"}
                        data-plasmic-override={overrides.button2}
                        className={classNames("__wab_instance", sty.button2)}
                        color2={"green"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dtf0T
                            )}
                            role={"img"}
                          />
                        }
                        size={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "compact"
                            : "compact"
                        }
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__zahar
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vYxze
                          )}
                        >
                          {"Coming Soon"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                </Stack__>
              </Stack__>
            </div>
            <BaryonFooter
              data-plasmic-name={"baryonFooter"}
              data-plasmic-override={overrides.baryonFooter}
              className={classNames("__wab_instance", sty.baryonFooter)}
              whitetextFooter={true}
            />
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  plugin: [
    "plugin",
    "navBar",
    "foreground",
    "pluginDetails",
    "foreground2",
    "columns",
    "h2",
    "compatibility",
    "h3",
    "touchDesignerLogo",
    "resolumeLogo",
    "unrealEngineLogo",
    "abletonLogo",
    "obsLogo",
    "pricing",
    "foreground3",
    "button2",
    "baryonFooter"
  ],

  navBar: ["navBar"],
  foreground: ["foreground"],
  pluginDetails: ["pluginDetails", "foreground2", "columns", "h2"],
  foreground2: ["foreground2", "columns", "h2"],
  columns: ["columns", "h2"],
  h2: ["h2"],
  compatibility: [
    "compatibility",
    "h3",
    "touchDesignerLogo",
    "resolumeLogo",
    "unrealEngineLogo",
    "abletonLogo",
    "obsLogo"
  ],

  h3: ["h3"],
  touchDesignerLogo: ["touchDesignerLogo"],
  resolumeLogo: ["resolumeLogo"],
  unrealEngineLogo: ["unrealEngineLogo"],
  abletonLogo: ["abletonLogo"],
  obsLogo: ["obsLogo"],
  pricing: ["pricing", "foreground3", "button2"],
  foreground3: ["foreground3", "button2"],
  button2: ["button2"],
  baryonFooter: ["baryonFooter"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPlugin__ArgProps,
          internalVariantPropNames: PlasmicPlugin__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPlugin__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "plugin") {
    func.displayName = "PlasmicPlugin";
  } else {
    func.displayName = `PlasmicPlugin.${nodeName}`;
  }
  return func;
}

export const PlasmicPlugin = Object.assign(
  // Top-level PlasmicPlugin renders the root element
  makeNodeComponent("plugin"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    foreground: makeNodeComponent("foreground"),
    pluginDetails: makeNodeComponent("pluginDetails"),
    foreground2: makeNodeComponent("foreground2"),
    columns: makeNodeComponent("columns"),
    h2: makeNodeComponent("h2"),
    compatibility: makeNodeComponent("compatibility"),
    h3: makeNodeComponent("h3"),
    touchDesignerLogo: makeNodeComponent("touchDesignerLogo"),
    resolumeLogo: makeNodeComponent("resolumeLogo"),
    unrealEngineLogo: makeNodeComponent("unrealEngineLogo"),
    abletonLogo: makeNodeComponent("abletonLogo"),
    obsLogo: makeNodeComponent("obsLogo"),
    pricing: makeNodeComponent("pricing"),
    foreground3: makeNodeComponent("foreground3"),
    button2: makeNodeComponent("button2"),
    baryonFooter: makeNodeComponent("baryonFooter"),
    // Metadata about props expected for PlasmicPlugin
    internalVariantProps: PlasmicPlugin__VariantProps,
    internalArgProps: PlasmicPlugin__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Plugin",
      description:
        "Cymatics music visualizer plugin for media servers and visual software tools.",
      ogImageSrc:
        "https://site-assets.plasmic.app/625a42e8eacfe1f7cdb72d99ccd2eee6.png",
      canonical: ""
    }
  }
);

export default PlasmicPlugin;
/* prettier-ignore-end */
