// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4dvBXLce6aZWcodsHuZ7oL
// Component: EPGJPtXx-yjL
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant,
  renderPlasmicSlot,
  useDollarState,
  useTrigger
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import * as pp from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4dvBXLce6aZWcodsHuZ7oL/projectcss
import sty from "./PlasmicButton2.module.css"; // plasmic-import: EPGJPtXx-yjL/css
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: IYnmkRggg6dZ/icon

createPlasmicElementProxy;

export const PlasmicButton2__VariantProps = new Array(
  "showStartIcon",
  "showEndIcon",
  "isDisabled",
  "shape",
  "size",
  "color2"
);

export const PlasmicButton2__ArgProps = new Array(
  "children",
  "startIcon",
  "endIcon",
  "link",
  "submitsForm",
  "target"
);

const $$ = {};

function PlasmicButton2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "showStartIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.showStartIcon
      },
      {
        path: "showEndIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.showEndIcon
      },
      {
        path: "isDisabled",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.isDisabled
      },
      {
        path: "shape",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.shape
      },
      {
        path: "size",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.size
      },
      {
        path: "color2",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.color2
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const [isRootFocusVisibleWithin, triggerRootFocusVisibleWithinProps] =
    useTrigger("useFocusVisibleWithin", {
      isTextInput: false
    });
  const triggers = {
    focusVisibleWithin_root: isRootFocusVisibleWithin
  };
  return (
    <Stack__
      as={"button"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.root___focusVisibleWithin]: triggers.focusVisibleWithin_root,
          [sty.rootcolor2_black]: hasVariant($state, "color2", "black"),
          [sty.rootcolor2_blue]: hasVariant($state, "color2", "blue"),
          [sty.rootcolor2_clear]: hasVariant($state, "color2", "clear"),
          [sty.rootcolor2_cyan]: hasVariant($state, "color2", "cyan"),
          [sty.rootcolor2_green]: hasVariant($state, "color2", "green"),
          [sty.rootcolor2_link]: hasVariant($state, "color2", "link"),
          [sty.rootcolor2_link_size_minimal]:
            hasVariant($state, "color2", "link") &&
            hasVariant($state, "size", "minimal"),
          [sty.rootcolor2_red]: hasVariant($state, "color2", "red"),
          [sty.rootcolor2_softBlue]: hasVariant($state, "color2", "softBlue"),
          [sty.rootcolor2_softGreen]: hasVariant($state, "color2", "softGreen"),
          [sty.rootcolor2_softRed]: hasVariant($state, "color2", "softRed"),
          [sty.rootcolor2_softSand]: hasVariant($state, "color2", "softSand"),
          [sty.rootcolor2_softYellow]: hasVariant(
            $state,
            "color2",
            "softYellow"
          ),
          [sty.rootcolor2_white]: hasVariant($state, "color2", "white"),
          [sty.rootcolor2_yellow]: hasVariant($state, "color2", "yellow"),
          [sty.rootisDisabled]: hasVariant($state, "isDisabled", "isDisabled"),
          [sty.rootshape_round]: hasVariant($state, "shape", "round"),
          [sty.rootshape_round_size_compact]:
            hasVariant($state, "shape", "round") &&
            hasVariant($state, "size", "compact"),
          [sty.rootshape_rounded]: hasVariant($state, "shape", "rounded"),
          [sty.rootshape_rounded_showEndIcon]:
            hasVariant($state, "showEndIcon", "showEndIcon") &&
            hasVariant($state, "shape", "rounded"),
          [sty.rootshape_rounded_size_compact]:
            hasVariant($state, "size", "compact") &&
            hasVariant($state, "shape", "rounded"),
          [sty.rootshape_sharp]: hasVariant($state, "shape", "sharp"),
          [sty.rootshowEndIcon]: hasVariant(
            $state,
            "showEndIcon",
            "showEndIcon"
          ),
          [sty.rootshowStartIcon]: hasVariant(
            $state,
            "showStartIcon",
            "showStartIcon"
          ),
          [sty.rootshowStartIcon_shape_rounded]:
            hasVariant($state, "shape", "rounded") &&
            hasVariant($state, "showStartIcon", "showStartIcon"),
          [sty.rootshowStartIcon_size_compact]:
            hasVariant($state, "size", "compact") &&
            hasVariant($state, "showStartIcon", "showStartIcon"),
          [sty.rootshowStartIcon_size_compact_showEndIcon]:
            hasVariant($state, "size", "compact") &&
            hasVariant($state, "showStartIcon", "showStartIcon") &&
            hasVariant($state, "showEndIcon", "showEndIcon"),
          [sty.rootsize_compact]: hasVariant($state, "size", "compact"),
          [sty.rootsize_compact_showEndIcon]:
            hasVariant($state, "size", "compact") &&
            hasVariant($state, "showEndIcon", "showEndIcon"),
          [sty.rootsize_minimal]: hasVariant($state, "size", "minimal")
        }
      )}
      data-plasmic-trigger-props={[triggerRootFocusVisibleWithinProps]}
    >
      {(hasVariant($state, "showStartIcon", "showStartIcon") ? true : false) ? (
        <div
          data-plasmic-name={"startIconContainer"}
          data-plasmic-override={overrides.startIconContainer}
          className={classNames(projectcss.all, sty.startIconContainer, {
            [sty.startIconContainercolor2_blue]: hasVariant(
              $state,
              "color2",
              "blue"
            ),
            [sty.startIconContainershowStartIcon]: hasVariant(
              $state,
              "showStartIcon",
              "showStartIcon"
            ),
            [sty.startIconContainershowStartIcon_shape_rounded]:
              hasVariant($state, "shape", "rounded") &&
              hasVariant($state, "showStartIcon", "showStartIcon")
          })}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <svg
                className={classNames(projectcss.all, sty.svg__z4G40)}
                role={"img"}
              />
            ),

            value: args.startIcon,
            className: classNames(sty.slotTargetStartIcon, {
              [sty.slotTargetStartIconcolor2_blue]: hasVariant(
                $state,
                "color2",
                "blue"
              ),
              [sty.slotTargetStartIconcolor2_clear]: hasVariant(
                $state,
                "color2",
                "clear"
              ),
              [sty.slotTargetStartIconcolor2_link]: hasVariant(
                $state,
                "color2",
                "link"
              ),
              [sty.slotTargetStartIconcolor2_softBlue]: hasVariant(
                $state,
                "color2",
                "softBlue"
              ),
              [sty.slotTargetStartIconcolor2_softGreen]: hasVariant(
                $state,
                "color2",
                "softGreen"
              ),
              [sty.slotTargetStartIconcolor2_softRed]: hasVariant(
                $state,
                "color2",
                "softRed"
              ),
              [sty.slotTargetStartIconcolor2_softSand]: hasVariant(
                $state,
                "color2",
                "softSand"
              ),
              [sty.slotTargetStartIconcolor2_softYellow]: hasVariant(
                $state,
                "color2",
                "softYellow"
              ),
              [sty.slotTargetStartIconcolor2_white]: hasVariant(
                $state,
                "color2",
                "white"
              ),
              [sty.slotTargetStartIconcolor2_yellow]: hasVariant(
                $state,
                "color2",
                "yellow"
              ),
              [sty.slotTargetStartIconshowStartIcon]: hasVariant(
                $state,
                "showStartIcon",
                "showStartIcon"
              )
            })
          })}
        </div>
      ) : null}
      <div
        data-plasmic-name={"contentContainer"}
        data-plasmic-override={overrides.contentContainer}
        className={classNames(projectcss.all, sty.contentContainer, {
          [sty.contentContainer___focusVisibleWithin]:
            triggers.focusVisibleWithin_root,
          [sty.contentContainercolor2_cyan]: hasVariant(
            $state,
            "color2",
            "cyan"
          ),
          [sty.contentContainercolor2_link]: hasVariant(
            $state,
            "color2",
            "link"
          ),
          [sty.contentContainercolor2_softSand]: hasVariant(
            $state,
            "color2",
            "softSand"
          ),
          [sty.contentContainerisDisabled]: hasVariant(
            $state,
            "isDisabled",
            "isDisabled"
          ),
          [sty.contentContainershape_rounded]: hasVariant(
            $state,
            "shape",
            "rounded"
          ),
          [sty.contentContainershowEndIcon]: hasVariant(
            $state,
            "showEndIcon",
            "showEndIcon"
          )
        })}
      >
        {renderPlasmicSlot({
          defaultContents: "Button",
          value: args.children,
          className: classNames(sty.slotTargetChildren, {
            [sty.slotTargetChildren___focusVisibleWithin]:
              triggers.focusVisibleWithin_root,
            [sty.slotTargetChildrencolor2_black]: hasVariant(
              $state,
              "color2",
              "black"
            ),
            [sty.slotTargetChildrencolor2_blue]: hasVariant(
              $state,
              "color2",
              "blue"
            ),
            [sty.slotTargetChildrencolor2_clear]: hasVariant(
              $state,
              "color2",
              "clear"
            ),
            [sty.slotTargetChildrencolor2_cyan]: hasVariant(
              $state,
              "color2",
              "cyan"
            ),
            [sty.slotTargetChildrencolor2_green]: hasVariant(
              $state,
              "color2",
              "green"
            ),
            [sty.slotTargetChildrencolor2_link]: hasVariant(
              $state,
              "color2",
              "link"
            ),
            [sty.slotTargetChildrencolor2_link_size_minimal]:
              hasVariant($state, "color2", "link") &&
              hasVariant($state, "size", "minimal"),
            [sty.slotTargetChildrencolor2_red]: hasVariant(
              $state,
              "color2",
              "red"
            ),
            [sty.slotTargetChildrencolor2_softBlue]: hasVariant(
              $state,
              "color2",
              "softBlue"
            ),
            [sty.slotTargetChildrencolor2_softGreen]: hasVariant(
              $state,
              "color2",
              "softGreen"
            ),
            [sty.slotTargetChildrencolor2_softRed]: hasVariant(
              $state,
              "color2",
              "softRed"
            ),
            [sty.slotTargetChildrencolor2_softSand]: hasVariant(
              $state,
              "color2",
              "softSand"
            ),
            [sty.slotTargetChildrencolor2_softYellow]: hasVariant(
              $state,
              "color2",
              "softYellow"
            ),
            [sty.slotTargetChildrencolor2_white]: hasVariant(
              $state,
              "color2",
              "white"
            ),
            [sty.slotTargetChildrencolor2_yellow]: hasVariant(
              $state,
              "color2",
              "yellow"
            ),
            [sty.slotTargetChildrenisDisabled]: hasVariant(
              $state,
              "isDisabled",
              "isDisabled"
            ),
            [sty.slotTargetChildrenshape_rounded]: hasVariant(
              $state,
              "shape",
              "rounded"
            ),
            [sty.slotTargetChildrenshowEndIcon]: hasVariant(
              $state,
              "showEndIcon",
              "showEndIcon"
            ),
            [sty.slotTargetChildrenshowStartIcon]: hasVariant(
              $state,
              "showStartIcon",
              "showStartIcon"
            ),
            [sty.slotTargetChildrensize_minimal]: hasVariant(
              $state,
              "size",
              "minimal"
            )
          })
        })}
      </div>
      {(hasVariant($state, "showEndIcon", "showEndIcon") ? true : false) ? (
        <div
          data-plasmic-name={"endIconContainer"}
          data-plasmic-override={overrides.endIconContainer}
          className={classNames(projectcss.all, sty.endIconContainer, {
            [sty.endIconContainercolor2_white]: hasVariant(
              $state,
              "color2",
              "white"
            ),
            [sty.endIconContainercolor2_yellow]: hasVariant(
              $state,
              "color2",
              "yellow"
            ),
            [sty.endIconContainershowEndIcon]: hasVariant(
              $state,
              "showEndIcon",
              "showEndIcon"
            )
          })}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg__qj1Wy)}
                role={"img"}
              />
            ),

            value: args.endIcon,
            className: classNames(sty.slotTargetEndIcon, {
              [sty.slotTargetEndIconcolor2_clear]: hasVariant(
                $state,
                "color2",
                "clear"
              ),
              [sty.slotTargetEndIconcolor2_link]: hasVariant(
                $state,
                "color2",
                "link"
              ),
              [sty.slotTargetEndIconcolor2_softBlue]: hasVariant(
                $state,
                "color2",
                "softBlue"
              ),
              [sty.slotTargetEndIconcolor2_softGreen]: hasVariant(
                $state,
                "color2",
                "softGreen"
              ),
              [sty.slotTargetEndIconcolor2_softRed]: hasVariant(
                $state,
                "color2",
                "softRed"
              ),
              [sty.slotTargetEndIconcolor2_softSand]: hasVariant(
                $state,
                "color2",
                "softSand"
              ),
              [sty.slotTargetEndIconcolor2_softYellow]: hasVariant(
                $state,
                "color2",
                "softYellow"
              ),
              [sty.slotTargetEndIconcolor2_white]: hasVariant(
                $state,
                "color2",
                "white"
              ),
              [sty.slotTargetEndIconcolor2_yellow]: hasVariant(
                $state,
                "color2",
                "yellow"
              ),
              [sty.slotTargetEndIconshowEndIcon]: hasVariant(
                $state,
                "showEndIcon",
                "showEndIcon"
              )
            })
          })}
        </div>
      ) : null}
    </Stack__>
  );
}

function useBehavior(props, ref) {
  const b = pp.useButton(
    PlasmicButton2,
    props,
    {
      showStartIconVariant: {
        group: "showStartIcon",
        variant: "showStartIcon"
      },
      showEndIconVariant: { group: "showEndIcon", variant: "showEndIcon" },
      isDisabledVariant: { group: "isDisabled", variant: "isDisabled" },
      contentSlot: "children",
      startIconSlot: "startIcon",
      endIconSlot: "endIcon",
      root: "root"
    },
    ref
  );
  return b;
}

const PlasmicDescendants = {
  root: ["root", "startIconContainer", "contentContainer", "endIconContainer"],
  startIconContainer: ["startIconContainer"],
  contentContainer: ["contentContainer"],
  endIconContainer: ["endIconContainer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicButton2__ArgProps,
          internalVariantPropNames: PlasmicButton2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicButton2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButton2";
  } else {
    func.displayName = `PlasmicButton2.${nodeName}`;
  }
  return func;
}

export const PlasmicButton2 = Object.assign(
  // Top-level PlasmicButton2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    startIconContainer: makeNodeComponent("startIconContainer"),
    contentContainer: makeNodeComponent("contentContainer"),
    endIconContainer: makeNodeComponent("endIconContainer"),
    // Metadata about props expected for PlasmicButton2
    internalVariantProps: PlasmicButton2__VariantProps,
    internalArgProps: PlasmicButton2__ArgProps,
    useBehavior
  }
);

export default PlasmicButton2;
/* prettier-ignore-end */
