import { AUDIO_DEFAULTS } from "../defaults.js";
import {
  RAYMARCH_MODAL_BASIS_CACHE_CAPACITY,
  RAYMARCH_MODAL_BASIS_HANDOFF_MODE_COUNT,
  RAYMARCH_MODAL_BASIS_CACHE_RESOLUTION,
  RAYMARCH_MODAL_BASIS_STEADY_MODE_COUNT,
  RAYMARCH_LIVE_SYNTHESIS_MODE_COUNT,
  getModalBasisCacheMaxRepresentableModeIndex,
} from "./raymarch/fieldCache.js";

export const MODAL_SEMANTIC_DESCRIPTOR_CAPACITY =
  AUDIO_DEFAULTS.maxModalFieldDescriptorModes;
export const MODAL_BASIS_ATLAS_PAGE_CAPACITY =
  RAYMARCH_MODAL_BASIS_STEADY_MODE_COUNT;
export const MODAL_BASIS_CACHE_PAGE_CAPACITY =
  RAYMARCH_MODAL_BASIS_CACHE_CAPACITY;
export const MODAL_BASIS_STEADY_MODE_COUNT =
  RAYMARCH_MODAL_BASIS_STEADY_MODE_COUNT;
export const MODAL_BASIS_HANDOFF_MODE_COUNT =
  RAYMARCH_MODAL_BASIS_HANDOFF_MODE_COUNT;
export const MODAL_LIVE_SYNTHESIS_MODE_COUNT =
  RAYMARCH_LIVE_SYNTHESIS_MODE_COUNT;
export const MODAL_BASIS_CACHE_RESOLUTION =
  RAYMARCH_MODAL_BASIS_CACHE_RESOLUTION;

export { getModalBasisCacheMaxRepresentableModeIndex };
