// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4dvBXLce6aZWcodsHuZ7oL
// Component: xamm2QscKBA7
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Button2 from "../../Button2"; // plasmic-import: EPGJPtXx-yjL/component
import { useScreenVariants as useScreenVariantspcuqpuXkf7V2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PcuqpuXKF7v2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4dvBXLce6aZWcodsHuZ7oL/projectcss
import sty from "./PlasmicSiteNavBar.module.css"; // plasmic-import: xamm2QscKBA7/css
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: F3iOqCFKuA-k/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: IYnmkRggg6dZ/icon
import HamburgerMenuSvgrepoComsvgIcon from "./icons/PlasmicIcon__HamburgerMenuSvgrepoComsvg"; // plasmic-import: yQSNegzl0PI8/icon

createPlasmicElementProxy;

export const PlasmicSiteNavBar__VariantProps = new Array();

export const PlasmicSiteNavBar__ArgProps = new Array();

const $$ = {};

function PlasmicSiteNavBar__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspcuqpuXkf7V2()
  });
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"siteNavBar"}
      data-plasmic-override={overrides.siteNavBar}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.siteNavBar
      )}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__k2VAf)}
      >
        <PlasmicImg__
          data-plasmic-name={"baryonBlackLogo"}
          data-plasmic-override={overrides.baryonBlackLogo}
          alt={""}
          className={classNames(sty.baryonBlackLogo)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly") ? "40px" : "40px"
          }
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly") ? "40px" : "40px"
          }
          src={{
            src: "/assets/plasmic/baryon/images/baryonLogoWhitesvg.svg",
            fullWidth: 2391,
            fullHeight: 2048,
            aspectRatio: 1.16748
          }}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__wvVC
          )}
        >
          <React.Fragment>
            <React.Fragment>{""}</React.Fragment>
            {
              <h3
                data-plasmic-name={"baryonTitle"}
                data-plasmic-override={overrides.baryonTitle}
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.baryonTitle
                )}
              >
                {"Baryon"}
              </h3>
            }

            <React.Fragment>{""}</React.Fragment>
          </React.Fragment>
        </div>
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__xjZU)}
        >
          <Button2
            data-plasmic-name={"visualizerNav"}
            data-plasmic-override={overrides.visualizerNav}
            className={classNames("__wab_instance", sty.visualizerNav)}
            color={"clear"}
            endIcon={
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg__gxND)}
                role={"img"}
              />
            }
            link={`/visualizer`}
            onClick={async event => {
              const $steps = {};
              $steps["goToHomepage"] = true
                ? (() => {
                    const actionArgs = { destination: `/visualizer` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        location.assign(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToHomepage"] != null &&
                typeof $steps["goToHomepage"] === "object" &&
                typeof $steps["goToHomepage"].then === "function"
              ) {
                $steps["goToHomepage"] = await $steps["goToHomepage"];
              }
            }}
            startIcon={
              <ChecksvgIcon
                className={classNames(projectcss.all, sty.svg__dfKum)}
                role={"img"}
              />
            }
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cmFbs
              )}
            >
              {"Visualizer"}
            </div>
          </Button2>
          <Button2
            data-plasmic-name={"pluginNav"}
            data-plasmic-override={overrides.pluginNav}
            className={classNames("__wab_instance", sty.pluginNav)}
            color={"clear"}
            endIcon={
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg___8NfWs)}
                role={"img"}
              />
            }
            link={`/plugin`}
            onClick={async event => {
              const $steps = {};
              $steps["goToPlugin"] = true
                ? (() => {
                    const actionArgs = { destination: `/plugin` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        location.assign(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToPlugin"] != null &&
                typeof $steps["goToPlugin"] === "object" &&
                typeof $steps["goToPlugin"].then === "function"
              ) {
                $steps["goToPlugin"] = await $steps["goToPlugin"];
              }
            }}
            startIcon={
              <ChecksvgIcon
                className={classNames(projectcss.all, sty.svg__wbSx3)}
                role={"img"}
              />
            }
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vpBu3
              )}
            >
              {"Plugin"}
            </div>
          </Button2>
          <Button2
            data-plasmic-name={"storyNav"}
            data-plasmic-override={overrides.storyNav}
            className={classNames("__wab_instance", sty.storyNav)}
            color={"clear"}
            endIcon={
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg__tlAb)}
                role={"img"}
              />
            }
            link={`/story`}
            onClick={async event => {
              const $steps = {};
              $steps["goToStory"] = true
                ? (() => {
                    const actionArgs = { destination: `/story` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        location.assign(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToStory"] != null &&
                typeof $steps["goToStory"] === "object" &&
                typeof $steps["goToStory"].then === "function"
              ) {
                $steps["goToStory"] = await $steps["goToStory"];
              }
            }}
            startIcon={
              <ChecksvgIcon
                className={classNames(projectcss.all, sty.svg__riKjd)}
                role={"img"}
              />
            }
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__flv78
              )}
            >
              {"Story"}
            </div>
          </Button2>
          <Button2
            data-plasmic-name={"artNav"}
            data-plasmic-override={overrides.artNav}
            className={classNames("__wab_instance", sty.artNav)}
            color={"clear"}
            endIcon={
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg__ijzde)}
                role={"img"}
              />
            }
            link={"https://foundation.app/@Baryon"}
            startIcon={
              <ChecksvgIcon
                className={classNames(projectcss.all, sty.svg__aoUrb)}
                role={"img"}
              />
            }
            submitsForm={true}
            target={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__apCKj
              )}
            >
              {"Art"}
            </div>
          </Button2>
          <Button2
            className={classNames("__wab_instance", sty.button2__axAYg)}
            color={"clear"}
            endIcon={
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg__kTpWy)}
                role={"img"}
              />
            }
            startIcon={
              <ChecksvgIcon
                className={classNames(projectcss.all, sty.svg__obuA3)}
                role={"img"}
              />
            }
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__o3Fm
              )}
            >
              {"Log in"}
            </div>
          </Button2>
          <Button2
            className={classNames("__wab_instance", sty.button2___0VPHf)}
            endIcon={
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg__n8NFd)}
                role={"img"}
              />
            }
            startIcon={
              <ChecksvgIcon
                className={classNames(projectcss.all, sty.svg__mEhMe)}
                role={"img"}
              />
            }
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___5Bzuj
              )}
            >
              {"Sign up"}
            </div>
          </Button2>
        </Stack__>
        {false ? (
          <div className={classNames(projectcss.all, sty.freeBox__pKwuc)}>
            <button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames(
                projectcss.all,
                projectcss.button,
                projectcss.__wab_text,
                sty.button
              )}
            >
              {"Sign up"}
            </button>
            <Button2
              className={classNames("__wab_instance", sty.button2__foqtm)}
              color={"clear"}
              endIcon={
                <Icon38Icon
                  className={classNames(projectcss.all, sty.svg__vdYjX)}
                  role={"img"}
                />
              }
              startIcon={
                <ChecksvgIcon
                  className={classNames(projectcss.all, sty.svg__e9Otq)}
                  role={"img"}
                />
              }
              submitsForm={true}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nVlKc
                )}
              >
                {"Log in"}
              </div>
            </Button2>
          </div>
        ) : null}
        <HamburgerMenuSvgrepoComsvgIcon
          className={classNames(projectcss.all, sty.svg___9Hx3O)}
          onClick={async event => {
            const $steps = {};
            $steps["runElementAction"] = true
              ? (() => {
                  const actionArgs = {};
                  return (({ tplRef, action, args }) => {
                    return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["runElementAction"] != null &&
              typeof $steps["runElementAction"] === "object" &&
              typeof $steps["runElementAction"].then === "function"
            ) {
              $steps["runElementAction"] = await $steps["runElementAction"];
            }
          }}
          role={"img"}
        />
      </Stack__>
    </Stack__>
  );
}

const PlasmicDescendants = {
  siteNavBar: [
    "siteNavBar",
    "baryonBlackLogo",
    "baryonTitle",
    "visualizerNav",
    "pluginNav",
    "storyNav",
    "artNav",
    "button"
  ],

  baryonBlackLogo: ["baryonBlackLogo"],
  baryonTitle: ["baryonTitle"],
  visualizerNav: ["visualizerNav"],
  pluginNav: ["pluginNav"],
  storyNav: ["storyNav"],
  artNav: ["artNav"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSiteNavBar__ArgProps,
          internalVariantPropNames: PlasmicSiteNavBar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSiteNavBar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "siteNavBar") {
    func.displayName = "PlasmicSiteNavBar";
  } else {
    func.displayName = `PlasmicSiteNavBar.${nodeName}`;
  }
  return func;
}

export const PlasmicSiteNavBar = Object.assign(
  // Top-level PlasmicSiteNavBar renders the root element
  makeNodeComponent("siteNavBar"),
  {
    // Helper components rendering sub-elements
    baryonBlackLogo: makeNodeComponent("baryonBlackLogo"),
    baryonTitle: makeNodeComponent("baryonTitle"),
    visualizerNav: makeNodeComponent("visualizerNav"),
    pluginNav: makeNodeComponent("pluginNav"),
    storyNav: makeNodeComponent("storyNav"),
    artNav: makeNodeComponent("artNav"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicSiteNavBar
    internalVariantProps: PlasmicSiteNavBar__VariantProps,
    internalArgProps: PlasmicSiteNavBar__ArgProps
  }
);

export default PlasmicSiteNavBar;
/* prettier-ignore-end */
