// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4dvBXLce6aZWcodsHuZ7oL
// Component: FKV3u0E4hZrB
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { useScreenVariants as useScreenVariantspcuqpuXkf7V2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PcuqpuXKF7v2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4dvBXLce6aZWcodsHuZ7oL/projectcss
import sty from "./PlasmicBaryonFooter.module.css"; // plasmic-import: FKV3u0E4hZrB/css
import LogosvgIcon from "./icons/PlasmicIcon__Logosvg"; // plasmic-import: pPVNZjSA1lJo/icon
import InstagramSvgrepoComsvgIcon from "./icons/PlasmicIcon__InstagramSvgrepoComsvg"; // plasmic-import: X2e01B-uxA5q/icon

createPlasmicElementProxy;

export const PlasmicBaryonFooter__VariantProps = new Array();

export const PlasmicBaryonFooter__ArgProps = new Array();

const $$ = {};

function PlasmicBaryonFooter__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspcuqpuXkf7V2()
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        hasGap={true}
        className={classNames(projectcss.all, sty.columns)}
      >
        <div
          data-plasmic-name={"column"}
          data-plasmic-override={overrides.column}
          className={classNames(projectcss.all, sty.column)}
        >
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__wg3Kr)}
          >
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"40px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"40px"}
              src={{
                src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMzkxIDIwNDgiPgogIDxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNMjM5MC4yMSAxMi4zODVjLTQ4OS43OCA3Ni42MTMtODY0LjQ4IDUwMC4zNzItODY0LjQ4IDEwMTEuNjQ1IDAgNTExLjIxIDM3NC42IDkzNC45MiA4NjQuMjcgMTAxMS42Mi01MS45OCA4LjEzLTEwNS4yNiAxMi4zNS0xNTkuNTIgMTIuMzUtNTY1LjU0IDAtMTAyNC00NTguNDYtMTAyNC0xMDI0UzE2NjQuOTQgMCAyMjMwLjQ4IDBjNTQuMzMgMCAxMDcuNjggNC4yMzIgMTU5LjczIDEyLjM4NXpNMCAxMi4zODVDNDg5Ljc3NCA4OC45OTggODY0LjQ3NiA1MTIuNzU3IDg2NC40NzYgMTAyNC4wM2MwIDUxMS4yMS0zNzQuNTk2IDkzNC45Mi04NjQuMjY4IDEwMTEuNjIgNTEuOTgyIDguMTMgMTA1LjI2IDEyLjM1IDE1OS41MjQgMTIuMzUgNTY1LjU0IDAgMTAyMy45OTgtNDU4LjQ2IDEwMjMuOTk4LTEwMjRTNzI1LjI3MiAwIDE1OS43MzIgMEMxMDUuMzk2IDAgNTIuMDQ4IDQuMjMyIDAgMTIuMzg1eiIgZmlsbD0iIzAwMCIvPgo8L3N2Zz4K",
                fullWidth: 2391,
                fullHeight: 2048,
                aspectRatio: 1.16748
              }}
            />

            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__q37Sy)}
            >
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {"Connect with us"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__aLqSt)}
              >
                <LogosvgIcon
                  className={classNames(projectcss.all, sty.svg__zmaZs)}
                  onClick={async event => {
                    const $steps = {};
                    $steps["goToHttpsxcombaryonofficial"] = true
                      ? (() => {
                          const actionArgs = {
                            destination: "https://x.com/baryonofficial"
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              location.assign(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToHttpsxcombaryonofficial"] != null &&
                      typeof $steps["goToHttpsxcombaryonofficial"] ===
                        "object" &&
                      typeof $steps["goToHttpsxcombaryonofficial"].then ===
                        "function"
                    ) {
                      $steps["goToHttpsxcombaryonofficial"] = await $steps[
                        "goToHttpsxcombaryonofficial"
                      ];
                    }
                  }}
                  role={"img"}
                />

                <InstagramSvgrepoComsvgIcon
                  className={classNames(projectcss.all, sty.svg__c9B5)}
                  onClick={async event => {
                    const $steps = {};
                    $steps["goToHttpsinstagramcombaryoneth"] = true
                      ? (() => {
                          const actionArgs = {
                            destination: "https://instagram.com/baryon.eth"
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              location.assign(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToHttpsinstagramcombaryoneth"] != null &&
                      typeof $steps["goToHttpsinstagramcombaryoneth"] ===
                        "object" &&
                      typeof $steps["goToHttpsinstagramcombaryoneth"].then ===
                        "function"
                    ) {
                      $steps["goToHttpsinstagramcombaryoneth"] = await $steps[
                        "goToHttpsinstagramcombaryoneth"
                      ];
                    }
                  }}
                  role={"img"}
                />
              </Stack__>
            </Stack__>
          </Stack__>
        </div>
      </Stack__>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "columns", "column", "img", "text"],
  columns: ["columns", "column", "img", "text"],
  column: ["column", "img", "text"],
  img: ["img"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBaryonFooter__ArgProps,
          internalVariantPropNames: PlasmicBaryonFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBaryonFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBaryonFooter";
  } else {
    func.displayName = `PlasmicBaryonFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicBaryonFooter = Object.assign(
  // Top-level PlasmicBaryonFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    column: makeNodeComponent("column"),
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicBaryonFooter
    internalVariantProps: PlasmicBaryonFooter__VariantProps,
    internalArgProps: PlasmicBaryonFooter__ArgProps
  }
);

export default PlasmicBaryonFooter;
/* prettier-ignore-end */
