// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4dvBXLce6aZWcodsHuZ7oL
// Component: lMG1kVVdP4CO
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useDollarState,
  useTrigger
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4dvBXLce6aZWcodsHuZ7oL/projectcss
import sty from "./PlasmicSkeumorphicToggle.module.css"; // plasmic-import: lMG1kVVdP4CO/css
import LayerBlur4Icon from "./icons/PlasmicIcon__LayerBlur4"; // plasmic-import: kTIJk4oQH_4i/icon

createPlasmicElementProxy;

export const PlasmicSkeumorphicToggle__VariantProps = new Array();

export const PlasmicSkeumorphicToggle__ArgProps = new Array();

const $$ = {};

function PlasmicSkeumorphicToggle__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const [
    isSkeumorphicToggleButton3Active,
    triggerSkeumorphicToggleButton3ActiveProps
  ] = useTrigger("usePressed", {});
  const triggers = {
    active_skeumorphicToggleButton3: isSkeumorphicToggleButton3Active
  };
  return (
    <div
      data-plasmic-name={"skeumorphicToggleButton3"}
      data-plasmic-override={overrides.skeumorphicToggleButton3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.skeumorphicToggleButton3
      )}
      data-plasmic-trigger-props={[triggerSkeumorphicToggleButton3ActiveProps]}
    >
      <div
        data-plasmic-name={"base3"}
        data-plasmic-override={overrides.base3}
        className={classNames(projectcss.all, sty.base3)}
      />

      <div
        data-plasmic-name={"outsideStroke3"}
        data-plasmic-override={overrides.outsideStroke3}
        className={classNames(projectcss.all, sty.outsideStroke3)}
      />

      <div
        data-plasmic-name={"insideStroke3"}
        data-plasmic-override={overrides.insideStroke3}
        className={classNames(projectcss.all, sty.insideStroke3)}
      />

      <div
        data-plasmic-name={"textFrame3"}
        data-plasmic-override={overrides.textFrame3}
        className={classNames(projectcss.all, sty.textFrame3)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___4FJz7
          )}
        >
          {"OFF"}
        </div>
      </div>
      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__r9EmC)}
        displayHeight={"19px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"19px"}
        loading={"lazy"}
        src={{
          src: "/assets/plasmic/baryon/images/ellipse11.svg",
          fullWidth: 19,
          fullHeight: 19,
          aspectRatio: 1
        }}
      />

      {(triggers.active_skeumorphicToggleButton3 ? true : false) ? (
        <div
          data-plasmic-name={"property1On"}
          data-plasmic-override={overrides.property1On}
          className={classNames(projectcss.all, sty.property1On)}
        >
          <div
            data-plasmic-name={"base"}
            data-plasmic-override={overrides.base}
            className={classNames(projectcss.all, sty.base)}
          />

          <div
            data-plasmic-name={"outsideStroke"}
            data-plasmic-override={overrides.outsideStroke}
            className={classNames(projectcss.all, sty.outsideStroke)}
          />

          <div
            data-plasmic-name={"insideStroke"}
            data-plasmic-override={overrides.insideStroke}
            className={classNames(projectcss.all, sty.insideStroke)}
          />

          <div
            data-plasmic-name={"textFrame"}
            data-plasmic-override={overrides.textFrame}
            className={classNames(projectcss.all, sty.textFrame)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aN3Pw
              )}
            >
              {"ON"}
            </div>
          </div>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__zNJxL)}
            displayHeight={"19px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"19px"}
            loading={"lazy"}
            src={{
              src: "/assets/plasmic/baryon/images/knob6.svg",
              fullWidth: 19,
              fullHeight: 19,
              aspectRatio: 1
            }}
          />

          <div
            data-plasmic-name={"maskGroup"}
            data-plasmic-override={overrides.maskGroup}
            className={classNames(projectcss.all, sty.maskGroup)}
          >
            <LayerBlur4Icon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />
          </div>
        </div>
      ) : null}
    </div>
  );
}

const PlasmicDescendants = {
  skeumorphicToggleButton3: [
    "skeumorphicToggleButton3",
    "base3",
    "outsideStroke3",
    "insideStroke3",
    "textFrame3",
    "property1On",
    "base",
    "outsideStroke",
    "insideStroke",
    "textFrame",
    "maskGroup",
    "svg"
  ],

  base3: ["base3"],
  outsideStroke3: ["outsideStroke3"],
  insideStroke3: ["insideStroke3"],
  textFrame3: ["textFrame3"],
  property1On: [
    "property1On",
    "base",
    "outsideStroke",
    "insideStroke",
    "textFrame",
    "maskGroup",
    "svg"
  ],

  base: ["base"],
  outsideStroke: ["outsideStroke"],
  insideStroke: ["insideStroke"],
  textFrame: ["textFrame"],
  maskGroup: ["maskGroup", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSkeumorphicToggle__ArgProps,
          internalVariantPropNames: PlasmicSkeumorphicToggle__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSkeumorphicToggle__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "skeumorphicToggleButton3") {
    func.displayName = "PlasmicSkeumorphicToggle";
  } else {
    func.displayName = `PlasmicSkeumorphicToggle.${nodeName}`;
  }
  return func;
}

export const PlasmicSkeumorphicToggle = Object.assign(
  // Top-level PlasmicSkeumorphicToggle renders the root element
  makeNodeComponent("skeumorphicToggleButton3"),
  {
    // Helper components rendering sub-elements
    base3: makeNodeComponent("base3"),
    outsideStroke3: makeNodeComponent("outsideStroke3"),
    insideStroke3: makeNodeComponent("insideStroke3"),
    textFrame3: makeNodeComponent("textFrame3"),
    property1On: makeNodeComponent("property1On"),
    base: makeNodeComponent("base"),
    outsideStroke: makeNodeComponent("outsideStroke"),
    insideStroke: makeNodeComponent("insideStroke"),
    textFrame: makeNodeComponent("textFrame"),
    maskGroup: makeNodeComponent("maskGroup"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicSkeumorphicToggle
    internalVariantProps: PlasmicSkeumorphicToggle__VariantProps,
    internalArgProps: PlasmicSkeumorphicToggle__ArgProps
  }
);

export default PlasmicSkeumorphicToggle;
/* prettier-ignore-end */
