name: Code Quality
on: [push, pull_request]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm prettier --check "**/*.{js,jsx,ts,tsx,json,md,yml,html,css}" --ignore-path .gitignore --ignore-path .prettierignore
      - name: Lint
        run: pnpm lint
